name: healthier2
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0
  flutter_svg: ^2.0.7
  select_form_field: ^2.2.0
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.8.4
  firebase_core: ^2.15.0
  flutter_local_notifications: ^15.1.0+1
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  intl: ^0.18.1
  rflutter_alert: ^2.0.7
  shared_preferences: ^2.2.0
  syncfusion_flutter_datepicker: ^22.2.9
  flutter_background_service: ^2.1.1
  device_info_plus: ^9.0.3
  flutter_speed_dial: ^7.0.0
  fluttertoast: ^8.2.2
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0

  flutter_lints: ^2.0.0
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  resize_behavior: shrink_only
  image_path: "assets/images/logo.png"  

flutter:
  uses-material-design: true
  fonts:
     - family: Roboto
       fonts:
         - asset: fonts/Roboto-Medium.ttf
         - asset: fonts/Roboto-Black.ttf
         - asset: fonts/Roboto-MediumItalic.ttf
         - asset: fonts/Roboto-Bold.ttf
         - asset: fonts/Roboto-Italic.ttf
         - asset: fonts/Roboto-Regular.ttf
         - asset: fonts/Roboto-Thin.ttf
         - asset: fonts/Roboto-ThinItalic.ttf
  assets:
     - assets/images/clinic.svg
     - assets/images/clinicians.png
