// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZND2EXSk02pzIKw1GGMlaqVcaSofHpng',
    appId: '1:352384205015:web:11fe419e8f2f78af8e7092',
    messagingSenderId: '352384205015',
    projectId: 'healthier2-90e64',
    authDomain: 'healthier2-90e64.firebaseapp.com',
    storageBucket: 'healthier2-90e64.appspot.com',
    measurementId: 'G-30B1SLN946',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAcyd1r09EHle8xCFULccItRJ1-SpWCzE',
    appId: '1:352384205015:android:dc458674c5afbf758e7092',
    messagingSenderId: '352384205015',
    projectId: 'healthier2-90e64',
    storageBucket: 'healthier2-90e64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy5mtKYxYkX7fSW2ROWyIeekp1wFB7ls4',
    appId: '1:352384205015:ios:49b2c53b32be7da48e7092',
    messagingSenderId: '352384205015',
    projectId: 'healthier2-90e64',
    storageBucket: 'healthier2-90e64.appspot.com',
    iosClientId: '352384205015-2sgevv36pi9c268f4beru616be3ne6c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthier2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy5mtKYxYkX7fSW2ROWyIeekp1wFB7ls4',
    appId: '1:352384205015:ios:c9002fef11de0f328e7092',
    messagingSenderId: '352384205015',
    projectId: 'healthier2-90e64',
    storageBucket: 'healthier2-90e64.appspot.com',
    iosClientId: '352384205015-32h80c2eii52kdqtputp7nkotm40de5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthier2.RunnerTests',
  );
}
